name: Test Schedule

on:
  schedule:
    - cron: '*/5 * * * *' # Запуск каждые 5 минут

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered on schedule!"
