name: Run Tests Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Запуск каждый день в 10:00

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

      - name: Notify on Errors
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.issues.create(
              owner: ${{ github.repository_owner }},
              repo: ${{ github.repository }},
              title: "Test Failure Alert",
              body: "Tests failed. Please check the logs."
            )

